cart/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import *

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('change-qty/', csrf_exempt(ChangeQuantityBasketView.as_view())),
    path('remove-basket/', csrf_exempt(RemoveFromBAsketView.as_view())),
]

footer/models.py
from ckeditor_uploader.fields import RichTextUploadingFormField
from django.db import models
from core.utils import CustomLogoField, CustomModel


class CompanyInformation(models.Model):
    # icon = CustomLogoField(blank=True)
    text = models.CharField(max_length=255, verbose_name="Տեքստ")
    name = models.CharField(max_length=255,  verbose_name='Դաշտի անուն')
    url = models.CharField(max_length=1000,  blank=True, null=True, verbose_name="Հղում")
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False, verbose_name='Դասավորել')

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Կոնտակտային տվյալ'
        verbose_name_plural = 'Կոնտակտային տվյալներ'


class FooTerCategory(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name="Անուն")
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False, verbose_name='Դասավորել')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Footer -ի բաժին'
        verbose_name_plural = 'Footer -ի բաժիններ'


class FooterItems(CustomModel):
    LOGIN_CHOICES = [
        ('logged', 'Օգտատերեր'),
        ('guests', 'Հյուրեր'),
    ]

    category = models.ForeignKey(FooTerCategory,
                                 on_delete=models.RESTRICT,
                                 blank=True,
                                 verbose_name='Բաժին',
                                 null=True)
    name = models.CharField(max_length=255, unique=True, verbose_name="Անուն")
    url = models.URLField(verbose_name="Ամբողջական հղում")
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False, verbose_name='Դասավորել')
    is_auth = models.CharField(max_length=120,
                               blank=True, null=True,
                               choices=LOGIN_CHOICES,
                               verbose_name='Ցուցադրել միայն մուտք գործած օգտատերերին')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Footer -ի հղումներ'
        verbose_name_plural = 'Footer -ի հղումներ'


class SocialShareButtons(CustomModel):
    icon = CustomLogoField()
    url = models.URLField(verbose_name='Ամբողջական հղում')
    name = models.CharField(max_length=255, unique=True, verbose_name="Անուն (alt)")
    my_order = models.PositiveIntegerField(default=0, blank=False, null=False, verbose_name='Դասավորել')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Սոց. ցանցի լոգո'
        verbose_name_plural = 'Սոց. ցանցերի լոգոներ'


class FooterMessengers(CustomModel):
    icon = CustomLogoField(blank=False, null=False)
    url = models.CharField(max_length=255, verbose_name="Հղում")

    class Meta:
        verbose_name = 'Messenger'
        verbose_name_plural = 'Messenger -ներ'

    def __str__(self):
        return f'{self.id}'


class FooterInformationText(CustomModel):
    text = models.TextField(verbose_name='Տեքստ')

    class Meta:
        verbose_name = 'Ինֆորմացիոն տեքստ'
        verbose_name_plural = 'Ինֆորմացիոն տեքստ'

    def __str__(self):
        return 'Ինֆորմացիոն տեքստ'

class FooterPartners(CustomModel):
    icon = CustomLogoField(blank=False, null=False, verbose_name='Լոգո')
    my_order = models.PositiveIntegerField(default=0, verbose_name='Դասավորել')
    alt_title = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return f'{self.id}'

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Գործընկեր'
        verbose_name_plural = 'Գործընկերներ'


class CardIcons(CustomModel):
    icon = CustomLogoField()
    my_order = models.PositiveIntegerField(default=0, verbose_name='Դասավորել')

    def __str__(self):
        return f'{self.id}'

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Վճարային քարտի լոգո'
        verbose_name_plural = 'Վճարային քարտերի լոգոներ'

header/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from core.utils import CustomModel, CustomLogoField


class Slider(CustomModel):
    image = CustomLogoField(blank=False,  verbose_name="Մեծ նկար")
    image_small = CustomLogoField(blank=False, verbose_name="Փոքր նկար")
    text = RichTextUploadingField(blank=True, null=True)
    url = models.URLField(blank=True, null=True, verbose_name="Ամբողջական հղում")
    my_order = models.PositiveIntegerField(default=0, verbose_name="Դասավորել")

    def __str__(self):
        return str(self.pk)

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Գլխավոր էջի սլայդ'
        verbose_name_plural = 'Գլխավոր էջի սլայդեր'


class Header(CustomModel):
    """ Header table """

    name = models.CharField(max_length=255, verbose_name='Անուն')
    icon = CustomLogoField(verbose_name='Լոգո', blank=True, null=True)
    url = models.CharField(max_length=300, blank=True, null=True, verbose_name="Ամբողջական հղում")
    my_order = models.PositiveIntegerField(default=0, verbose_name="Դասավորել")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.url and not self.url.endswith('/'):
            self.url += '/'
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['my_order']

templates/includes/about_category_item.html
{% load static %}
<div class="swiper-slide {% if item.id == about_us.id %}active{% endif %}">
    <div class="hab-block text-center">
        <a href="{% if item.is_main %}{% url 'about_us' %}{% else %}{{ item.get_absolute_url }}{% endif %}">
            <figure>
                <img src="{% if item.logo %}{{ item.logo.url }}{% else %}{% static 'img/test-icons/hab-1.png' %}{% endif %}"
                     alt="">
            </figure>
            <div class="hab-name">
                <h3>{{ item.title|safe }}</h3>
            </div>
        </a>
    </div>
</div>

templates/includes/author_item.html
{% load i18n %}
{% load static %}
<article class="authors-item">
    <div class="authors-header">
        <a href="{{ author.get_absolute_url }}">
            <figure>
                <img src="{% if author.image %}{{ author.image.url }}{% else %}https://armtmm.com/media/1234-min.jpg{% endif %}" class="cover" loading="lazy"
                     alt="{{ author.name }}">
            </figure>
        </a>
    </div>
    <div class="authors-footer">
        <h2 class="line-clamp2">{{ author.name }}</h2>
        <a href="{{ author.get_absolute_url }}" class="button transparent normal">{% trans 'Մանրամասն' %}
            <img src="{% static 'img/icons/butt-art.svg' %}" alt="{% trans 'Մանրամասն' %}">
        </a>
    </div>
</article>

templates/includes/blog.html
{% load static %}
{% load i18n %}
<div class="col col-3">
    <article class="blog-item">
        <div class="blog-article-header">
            <figure>
                <a href="{{ blog.get_absolute_url }}">
                    <img src="{% if blog.image %}{{blog.image.url}}{% else %}{% static 'defaults/blog_default.jpg' %}{% endif %}"
                         alt="{{ blog.title }}"></a>
            </figure>
            <div class="blog-views calendars align-items-center">
                <div class="calendar-on align-items-center">
                    <span>{{blog.created_at|date:"Y-m-d H:i"}}</span>
                </div>
                <div class="views-on align-items-center">
                    <img src="{% static 'img/icons/eye.svg' %}" class="view-icon" alt="{% trans 'Դիտումների քանակ' %}">
                    <span>{{ blog.views_count }}</span>
                </div>
            </div>
        </div>
        <div class="blog-article-footer">
            <h4 class="blog-art-heading align-items-center">
                <a href="{{ blog.get_absolute_url }}" class="line-clamp2">{{blog.title}}</a>
            </h4>
            {% if blog.short_description %}
                {{ blog.short_description|safe }}
            {% endif %}
            <a href="{{ blog.get_absolute_url }}" class="button transparent normal">{% trans 'Մանրամասն' %}</a>
        </div>
    </article>
</div>

templates/includes/categories_list.html
<!-- Categories list for category page -->

   <nav class="block-content">
      <ul id="cat-names">
          {% if categories.first.parent %}
          {% for categ in categories %}
               <li class="">
                   <a href="{{categ.get_absolute_url}}" class="sub-tit {% if categ.get_absolute_url in request.get_full_path %}active{% endif %}">{{ categ.title }}</a>
                </li>
            {% endfor %}
          {% else %}
          
         {% for categ in categories %}

            <li class="">
               <a href="{{categ.get_absolute_url}}" class="sub-tit {% if categ.get_absolute_url in request.get_full_path %}active{% endif %}">{{ categ.title }}</a>
               {% if categ.children.count %}
               <ul>
                   {% for ct in categ.children.all %}
                  <li class="sub-menu">
                     <a href="{{ ct.get_absolute_url }}" class="{% if ct.get_absolute_url in request.get_full_path %}active{% endif %}">{{ ct.title }}</a>
                  </li>
                  {% endfor %}
               </ul>
               {% endif %}
            </li>
         {% endfor %}
         {% endif %}

      </ul>
   </nav>

templates/includes/filter.html
{% load static %}
{% load i18n %}
{% load unique %}
{% load currency %}
{% currency_context %}
<div class="nav-offcanvas-filter">
    <div class="filter_menu_container">
        <div class="filter_menu_content">
            <div class="filter-header d-none">
                <div class="widget-heading flex-center-between">
                    <span class="widget-title">{% trans 'Ֆիլտրեր' %}</span>
                    <img src="{% static 'img/icons/catalog-close.svg' %}" id="offFilterClose" class="close"
                         alt="Close menu">
                </div>
            </div>
            <div class="filter-widget-content">
                <div class="params-on-tit m-none">
                    <h3>
                        <img src="{% static 'img/icons/filter.svg' %}" alt="{% trans 'Ֆիլտրեր' %}">
                        <span>{% trans 'Ֆիլտրեր' %}</span>
                    </h3>
                </div>
                <form method="get" class="filters-periflowers" id="allFilter" onchange="filter()">
                    <div class="filter-params">
                        <div class="filter-params-title">
                            <h4 class="filter-params-hint flex-center-between">{% trans 'Գին' %}
                                <img src="{% static 'img/icons/cat-down.svg' %}" class="cat-left border-icons">
                            </h4>
                        </div>

                        <div class="filter-params-content">
                            <div class="range_slid flex-center-evenly">
                                <span><span class="field-labels">{% trans 'Մին' %}.</span><br>
                                    <input type="number" value="{% if request.GET.min_price %}{{ request.GET.min_price }}{% else %}{{ min_price_val|currency:request.session.currency|floatformat:0 }}{% endif %}"
                                           min="{{ min_price_val|currency:request.session.currency|floatformat:0 }}"
                                           max="{{ max_price_val|currency:request.session.currency|floatformat:0 }}"
                                           id="min_price" name="min_price">
                                </span>
                                <span><span class="field-labels">{% trans 'Մաքս' %}.</span><br>
                                    <input type="number" value="{% if request.GET.max_price %}{{ request.GET.max_price }}{% else %}{{ max_price_val|currency:request.session.currency|floatformat:0 }}{% endif %}"
                                           min="{{ min_price_val|currency:request.session.currency|floatformat:0 }}"
                                           max="{{ max_price_val|currency:request.session.currency|floatformat:0 }}"
                                           id="max_price" name="max_price">
                                </span>
                            </div>
                        </div>
                    </div>
                    {% if two_input_fields %}

                        <div class="filter-params">
                            <div class="filter-params-title">
                                <h4 class="filter-params-hint flex-center-between">{% trans 'Չափսեր' %}
                                    <img src="{% static 'img/icons/cat-down.svg' %}" class="cat-left border-icons">
                                </h4>
                            </div>
                            {% for two_input_field in two_input_fields %}
                                <div class="filter-params-content">
                                    <p class="filter-sub-name"><b>{{ two_input_field.title }}</b></p>
                                    <div class="range_slid flex-center-evenly">
                                        <span>
                                            <span class="field-labels">{% trans 'Մին' %}.</span><br>
                                            <input type="number" value="{{ two_input_field|get_min_val:category }}"
                                                   min="" max="" id="" name="min_{{ two_input_field.filter_key }}">
                                        </span>
                                        <span><span class="field-labels">{% trans 'Մաքս' %}.</span><br>
                                            <input type="number" value="{{ two_input_field|get_max_val:category }}"
                                                   min="" max="" id="" name="max_{{ two_input_field.filter_key }}">
                                        </span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                    {% endif %}
                    {% if colors %}
                        <div class="filter-params">
                            <div class="filter-params-title">
                                <h4 class="filter-params-hint flex-center-between">{% trans 'Գույն' %}
                                    <img src="{% static 'img/icons/cat-down.svg' %}" class="cat-left border-icons">
                                </h4>
                            </div>
                            <div class="filter-params-content">
                                {% for color in colors %}
                                    <div class="box-list">
                                        <label class="checkbox-design align-items-center">
                                            <input
                                                    type="checkbox"
                                                    class="color check"
                                                    value="{{ color.title }}"
                                                    id="id_colors_{{ forloop.counter }}"
                                                    name="color"
                                                    {% for k,v in request.GET.lists %}
                                                        {% if color.title in v %}
                                                    checked
                                                        {% endif %}
                                                    {% endfor %}
                                            >
                                            <span class="checkbox-square"></span>
                                            <span class="color-type" style="background-color:{{ color.color_code }}">
                                        </span>{{ color.title }}
                                        </label>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}

                    {% for field in filter_fields %}
                        <div class="filter-params">
                            <div class="filter-params-title">
                                <h4 class="filter-params-hint flex-center-between">{{ field.title }}
                                    <img src="{% static 'img/icons/cat-down.svg' %}" class="cat-left border-icons">
                                </h4>
                            </div>
                            <div class="filter-params-content">
                                {% for feat_val in field.productfeature_set.all|unique %}

                                    <div class="box-list">
                                        <label class="checkbox-design align-items-center">
                                            <input
                                                    type="checkbox"
                                                    class="color check"
                                                    value="{{ feat_val.title }}"
                                                    {% for k,v in request.GET.lists %}
                                                        {% if feat_val.title in v %}
                                                    checked{% endif %}
                                                    {% endfor %}
                                                    id="{{ forloop.counter }}__{{ field.filter_key }}"
                                                    name="{{ field.filter_key }}">
                                            <span class="checkbox-square"></span>{{ feat_val }}
                                        </label>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </form>
            </div>
        </div>
    </div>
</div>
<div class="filter_menu_overlay"></div>

templates/includes/filtered_item.html
{% load i18n %}
{% if page_obj.paginator.count  %}
    <div class="row full-ban">     
        {% for product in page_obj %}    
        <div class="col col-3">
            {% include 'includes/product.html' %}
        </div>         
        {% endfor %}                           
    </div>
    {% if page_obj.paginator.num_pages > 1 %}

    {% include 'includes/pagination.html' %}
    {% endif %}
{% else %}
  {% trans 'Որոնման արդյունքում ոչինչ չգտնվեց' %}
{% endif %}

templates/includes/footer.html
{% load static %}{% load linkfilter %}{% load i18n %}
<footer>
    <div class="only-footer">
        <div class="cnt">
            <div class="row foot-flex">
                <div class="col col-auto">
                    <div class="footer-item">
                        <h4>{% trans 'Կապ' %}</h4>
                        <div class="items-all">
                            {% if footer_messengers %}
                                <ul class="social_footer align-items-center">
                                        {% for i in footer_messengers %}
                                        <li>
                                            <a href="{% if i.url %}{{ i.url }}{% else %}javascript:void(0);{% endif %}"
                                               target="_blank"> <img src="{{ i.icon.url }}" alt="{% trans 'Կապ' %}">
                                            </a>
                                        </li>
                                        {% endfor %}
                                </ul>
                            {% endif %}
                            {% if company_information %}
                                <ul class="fc-info">
                                    {% for i in company_information %}
                                        <li>
                                            <span class="cf_name">{{ i.name }}</span>
                                            <a href="{% if i.url %}{{ i.url }}{% else %}javascript:void(0);{% endif %}">
                                                {{ i.text|safe}}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% for categ in footer_categories %}
                    <div class="col col-auto">
                        <div class="footer-item">
                            <h4>{{ categ.name }}</h4>
                            <div class="items-all">
                                <ul>
                                    {% for link in categ.footeritems_set.all|filter_links:trigger %}
                                        <li><a href="{{ link.url }}">{{ link.name|safe }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="col col-auto">
                    <div class="footer-item">
                        <h4>{% trans 'Վճարման Եղանակներ' %}</h4>
                        <div class="items-all">
                            <ul class="f-pay-icons align-items-center">
                                {% for card_icon in card_icons %}
                                    <li><img src="{{ card_icon.icon.url }}" alt="{% trans 'Վճարման Եղանակներ' %}"></li>
                                {% endfor %}
                            </ul>
                            <p class="foot_p-one"><!-- Machanents.com {% trans 'website represents Armenia' %}--></p> 
                            <h5>{% trans 'Հետևեք Մեզ' %}</h5>
                            {% if footer_follow_icons %}
                                <ul class="soc-icons d-flex">
                                    {% for ff in footer_follow_icons %}
                                    <li>
                                        <a target="_blank" href="{{ ff.url }}">
                                            <img src="{{ ff.icon.url }}" alt="{{ ff.name }}">
                                        </a>
                                    </li>
                                {% endfor %}
                                </ul>
                            {% endif %}
                            {% if info_text %}
                                <p class="foot_p-two">{{ info_text.text }}</p>
                            {% endif %}
                            {% if footer_partners %}
                                <ul class="partners align-items-center">
                                    {% for p in footer_partners %}
                                        <li><img src="{{ p.icon.url }}" alt="1"></li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="footer-bot text-center">
            <div class="logo-create">
                <div class="d-none footer-logo">
                    <img src="{% static 'img/f-logo.svg' %}" alt="Machanents.com">
                </div>
                <p>© {{ year }} Machanents Worldwide Shopping || {% trans 'Բոլոր իրավունքները պաշտպանված են' %}
                    <br>{% trans 'Design and Development by ' %} <a href="https://gios.am/" target="_blank">{% trans '"GIOS" LLC' %}</a>
                </p>
            </div>
        </div>
    </div>
</footer>
<div class="message-container">
    <div class="message success hidden" id="Messagebasket">
        <p>{% trans "Ընտրված ապրանքը զամբյուղում է" %}</p>
    </div>
</div>

templates/includes/pagination.html
{% load my_url %}
{% load i18n %}
{% if page_obj.paginator.num_pages > 1 %}
<div class="align-items-center">
    <div class="number-show-pagination m-none">
        <span>{% trans 'էջ' %} <b>{{page_obj.number}}</b> {% trans 'ից' %} {{page_obj.paginator.num_pages }}</span>
    </div>

    <nav class="pagination">
        <ul class="page-numbers">
        
            {% if page_obj.has_previous %}
                <li><a class="prev page-numbers" href="{% my_url 1 'page' request.GET.urlencode %}">←</a>
                </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if num == page_obj.number %}
                    <li><span aria-current="page"
                              class="page-numbers current">{{ num }}</span></li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li><a class="page-numbers" href="{% my_url num 'page' request.GET.urlencode %}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li>
                    <a class="next page-numbers" href="{% my_url page_obj.next_page_number 'page' request.GET.urlencode %}">→</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endif %}

templates/includes/product.html
{% load currency %}
{% currency_context %}
{% load static %}
{% load i18n %}
{% load unique %}
<div class="product-item">
    <div class="prod-item-img">
        <!-- New Sale icon -->
            {% if product.is_new and product.sale < 1 %}
            <span class="ns-prod prod-sale">{% trans 'Նորույթ' %}</span>
            {% elif not product.is_new and product.sale > 0 %}
            <span class="ns-prod prod-new">{% trans 'Խնայել' %} {{product.get_sale_percent}}%</span>
            {% elif product.sale > 0 and product.is_new %}
            <span class="ns-prod prod-new">{% trans 'Խնայել' %} {{product.get_sale_percent}}%</span>
            <span class="ns-prod prod-sale">{% trans 'Նորույթ' %}</span>
            {% endif %}
        <!-- New Sale icon end -->

        <!-- Wish list -->
        {% if not '/wishlist/' in  request.get_full_path %}

        <button  data-product="{{ product.id }}" data-url="{% url 'add_to_wish' %}" class="wish-list-icon flex-content-center wishlistAdd {% if product.id  in wish_ids %}active{% endif %} addTOWISH-{{ product.id }}">
            <svg class="{% if product.id  in wish_ids %}active{% endif %}" xmlns="http://www.w3.org/2000/svg" width="19" height="18" viewBox="0 0 19 18" fill="none">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M9.52645 16.8528C7.62716 15.6839 5.86029 14.3082 4.25744 12.7503C3.13057 11.6284 2.27269 10.2606 1.74952 8.75174C0.808066 5.82479 1.90775 2.474 4.98529 1.48235C6.60273 0.961654 8.36921 1.25926 9.73214 2.28207C11.0956 1.2605 12.8615 0.963004 14.479 1.48235C17.5565 2.474 18.6641 5.82479 17.7227 8.75174C17.1995 10.2606 16.3416 11.6284 15.2148 12.7503C13.6119 14.3082 11.845 15.6839 9.94575 16.8528L9.74006 16.9808L9.52645 16.8528Z" stroke="#181202" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
        </button>
        {% else %}

        <button data-product="{{product.id}}" data-url="{% url 'add_to_wish' %}" class="wish-list-icon wish-page flex-content-center wishlistAdd active addTOWISH-{{product.id}}">
            <span class="delete_prod_wish">×</span>
        </button>
        {% endif %}
        <a href="{{ product.get_absolute_url }}">
            <img src="{{product.main_photo.url}}" class="cover swiper-lazy main-prb-img">
        </a>
      </div>
    <div class="prod-item-desc">
        <div class="prod-item-name align-items-center">
            <a href="{{ product.get_absolute_url }}" class="line-clamp2">{{product.title|title}}</a>
        </div>
        <div class="prod-item-price">
            {% if product.sale > 0 %}
            <span class="new-price">
                <span class="wh-point">{{ product.sale|currency:request.session.currency|floatformat:0 }}</span>
                <span class="valyuta">{{request.session.currency}}</span>
                {% if request.session.currency != 'USD' %}
                    <span class="valyuta-dollar wh-point">($ {{ product.sale|usdconverter }})</span>
                {% endif %}
            </span>
            <s>
                <span class="old-price">
                    <span class="wh-point">{{ product.price|currency:request.session.currency|floatformat:0 }}</span>
                    <span class="valyuta">{{request.session.currency}}</span>
                </span>
            </s>
            {% else %}
            <span class="new-price">
                <span class="wh-point">{{ product.price|currency:request.session.currency|floatformat:0 }}</span>
                <span class="valyuta">{{request.session.currency}}</span>
                {% if request.session.currency != 'USD' %}
                    <span class="valyuta-dollar wh-point">($ {{ product.price|usdconverter }})</span>
                {% endif %}
            </span>
            {% endif %}
        </div>
        <div class="prod-add-cart">
            {% if not  product.productfeature_set.all|filter_feature %}
            <button type="button" class="flex-content-center button dark addcart" onclick="addToCart({{product.id}})">
                <img src="{% static 'img/icons/cart-prod.svg' %}" alt="{% trans 'Ավելացնել զամբյուղը' %}" >{% trans 'Ավելացնել' %}
            </button>
            {% else %}
            <a href="{{ product.get_absolute_url }}" class="flex-content-center button dark addcart">
                {% trans 'Ընտրել' %}
            </a>
            {% endif %}
{#            {% if not product.allowed_buying %}#}
{#            <a href="{{ product.get_absolute_url }}" class="flex-content-center button dark addcart" style="display: none;">#}
{#                {% trans 'Հարցում' %}#}
{#            </a>#}
{#            {% endif %}#}
        </div>
    </div>
</div>

templates/includes/tagmanager.html
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PWC85ZZ');</script>
<!-- End Google Tag Manager -->

templates/includes/tv_item.html
<div class="col col-2">
    <div class="tv-block">
        <div class="tv-block-img">
            {% if video.video_file and not video.video_iframe %}
            <iframe width="560"
                    height="315"
                    src="{{ video.video_file.url }}"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen>
            </iframe>
            {% else %}
                {{ video.video_iframe|safe }}
            {% endif %}
        </div>
    </div>
</div>